/* eslint-disable */
// Interactive setup helper for Emil Bridge Supervisor
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(r => rl.question(q, r));

async function main() {
  console.log('');
  console.log('═══════════════════════════════════════════');
  console.log('  Emil Bridge Supervisor — Setup');
  console.log('═══════════════════════════════════════════');
  console.log('');

  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('.env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  const appId = await ask('Base44 App ID: ');
  const token = await ask('Base44 Service Token: ');
  const apiUrl = await ask('Base44 API URL (Enter for default): ') || 'https://app.base44.com/api';
  const repoPath = await ask('Bridge repo path (e.g. C:\\Emil\\desktop-control-bridge): ');
  const port = await ask('Bridge port (Enter for 47821): ') || '47821';
  const pollMs = await ask('Poll interval ms (Enter for 7000): ') || '7000';
  const heartbeatPort = await ask('Heartbeat port (Enter for 47900): ') || '47900';

  const envContent = `# Emil Bridge Supervisor Configuration
# Generated by setup.js on ${new Date().toISOString()}

BASE44_APP_ID=${appId}
BASE44_SERVICE_TOKEN=${token}
BASE44_API_URL=${apiUrl}

BRIDGE_REPO_PATH=${repoPath}
BRIDGE_ENV_PATH=
BRIDGE_PORT=${port}
BRIDGE_PROCESS_NAME=node

POLL_INTERVAL_MS=${pollMs}
HEARTBEAT_INTERVAL_MS=30000
HEARTBEAT_PORT=${heartbeatPort}

MAX_RESTARTS_PER_HOUR=2
COMMAND_EXPIRY_SECONDS=300
`;

  fs.writeFileSync(envPath, envContent);
  console.log('');
  console.log(`✓ .env file written to ${envPath}`);
  console.log('');
  console.log('Next steps:');
  console.log('  1. Run: node supervisor.js');
  console.log('  2. Or install as a Windows service (see README)');
  console.log('');
  rl.close();
}

main();